services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=courses"
      - "MYSQL_PASSWORD=3778"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=root"
    ports:
      - "3306:3306"
